name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
      id-token: write
      security-events: write

    env:
      PUSH_IMAGE: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and optionally push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: ${{ env.PUSH_IMAGE }}
        tags: |
            ghcr.io/tsviz/tsvi-spring-test:latest
            ghcr.io/tsviz/tsvi-spring-test:${{ github.sha }}
            ghcr.io/tsviz/tsvi-spring-test:${{ github.ref_name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: "Release ${{ github.ref_name }} of the Docker image - tsvi-spring-test - built and pushed to GitHub Container Registry. Direct link to the image: [ghcr.io/tsviz/tsvi-spring-test:${{ github.ref_name }}](https://ghcr.io/tsviz/tsvi-spring-test:${{ github.ref_name }})"